### ISSUE TITLE
Dont work on Nextcloud25

### ISSUE THREAD

**Issue by Chiller2019** [powerpaul17/nc_money#19]
![NC_Money](https://user-images.githubusercontent.com/50303399/198285564-9c844b10-f419-495b-94e2-a33acd1377ab.png)

Its fixable?
OS: Ubuntu 20
NC-Version: 25
Error: TypeError: Cannot assign null to property OC\Core\Controller\PreviewController::$userId of type string

**Comment by powerpaul17** [comment]
This does not seem to be a problem with the app. Did you try and create an account to see if it works. Currently there is nothing displayed when you start the app, I am working on this..

**Comment by Chiller2019** [comment]
> This does not seem to be a problem with the app. Did you try and create an account to see if it works. Currently there is nothing displayed when you start the app, I am working on this..

Yeahr, because, its possible to click on the three dots but, they dont open the dropdown-menu. This is the reason why I cant create a account.

**Comment by powerpaul17** [comment]
> Yeahr, because, its possible to click on the three dots but, they dont open the dropdown-menu. This is the reason why I cant create a account. - Exactly.

Yes, you're right, I tried it on NC 25 and it does not work. I'll have a look at it.

**Comment by powerpaul17** [comment]
Fixed in 794f9d5d0864166347624484da82928cbfcd8acb

**Comment by Chiller2019** [comment]
Yes, works perfectly. Thx vm!
+1 for this App

**Comment by powerpaul17** [comment]
Thanks for reporting the problem :slightly_smiling_face:

**Comment by RandomNinjaAtk** [comment]
Just added the app, also cannot add an account. The "..." icon works and shows a pop up that gives the option to: `+ Add Account`

But clicking it does nothing. Tried both FireFox and Chrome.

**Comment by powerpaul17** [comment]
@RandomNinjaAtk Can you provide a bit more information please? What app version, is there an error in the console?

**Comment by RandomNinjaAtk** [comment]
@powerpaul17 App is version:  0.9.0 :: There is no error message displayed, just nothing happens when you click the link. I'm assuming something should happen, but I've never used the app before previously. So I do not know what should be expected, I just know it should do something.

I looked for a relevant log file, didn't find one. I'm using the linuxserver.io docker for nextcloud. Did not notice any errors in the console output.

**Comment by powerpaul17** [comment]
Hello again, I released an update? Can you please try again and see if it's working now? Thanks.

**Comment by RandomNinjaAtk** [comment]
The menu changed slightly in behavior, but clicking the + icon to add an account still doesn't do anything.

App version 0.11.1

**Comment by powerpaul17** [comment]
Ok, is there any error in the browser console? Maybe in the network log?

**Comment by RandomNinjaAtk** [comment]
![image](https://user-images.githubusercontent.com/8386416/205673500-63d1fd93-e4db-4b21-b2af-8762b5134cef.png)

I see a network request also that comes back with error 500. The pic is chrome's console for the click.

**Comment by powerpaul17** [comment]
Ok, thanks for the screenshot. That explains why it's not working. Unfortunately error 500 is an internal server error.. Can you click on the failed request in the "network" tab and see if there is a response there, please?
